# 根据springboot 对application加载的顺序定制通用的配置, 具体的服务下不要再使用application.yml

spring:
  codec:
    logRequestDetails: true
  servlet:
    multipart:
      max-file-size: 275661011
      max-request-size: 275661011
  task:
    scheduling:
      pool:
        size: 8  #更改定时任务线程池的线程大小
  mvc:
    log-request-details: true #debug下打印请求参数
    servlet:
      load-on-startup: 1
    hidden-method:
      filter:
        enabled: true
  jackson:
    time-zone: GMT+8:00
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 120000
      maximum-pool-size: 20
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
  tomcat:
    max-connections: 10000
    threads:
      max: 10000
      min-spare: 100
  compression:
    enabled: true
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
feign:
  okhttp:
    enabled: false
  compression:
    request:
      enabled: true
      mime-types: ['text/xml', 'application/xml','application/json','text/plain']
    response:
      enabled: true
      useGzipDecoder: true

---
spring:
  profiles: dev
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace
#    demo:
#      serviceb:
#        remote: debug
feign:
  client:
    config:
      default:
        loggerLevel: FULL
