eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
  profiles:
    active: '@spring.profiles.active@'



---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8761

---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8762
